version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/lib"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/derive"
    schedule:
      interval: "weekly"
